# Generated by Django 3.0.6 on 2020-07-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('post_description', models.TextField()),
                ('post_title', models.CharField(max_length=90)),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
